@extends('showing')

@section('heading')
<h4>Schedual</h4>
@endsection

@section('table')
<div class="table-responsive">
  <table  id="datatable" class="table table-striped table-bordered" >
    <thead>
      <tr>
        <th>DayOfTheWeek</th>
        <th>Morning</th>
        <th>Afternoon</th>
        <th>Evening</th>
      </tr>
    </thead>
    <tbody>
      @foreach($scheduals as $schedual)
      <tr>
        <td>{{$schedual->wod}}</td>
        <td>
          @if(!is_null($schedual->start[0]))
             @if(!is_null($schedual->end[0]))
             {{$schedual->start[0]}}-{{$schedual->end[0]}}
           @else
            Not-available
              @endif
        @else
           Not-available
         @endif
        </td>
        <td>
          @if(!is_null($schedual->start[1]))
            @if(!is_null($schedual->end[1]))
            {{$schedual->start[1]}}-{{$schedual->end[1]}}
          @else
           Not-available
             @endif
        @else
           Not-available
         @endif
        </td>
        <td>
            @if(!is_null($schedual->start[2]))
              @if(!is_null($schedual->end[2]))
              {{$schedual->start[2]}}-{{$schedual->end[2]}}
               @else
                Not-available
               @endif
           @else
           Not-available
           @endif
        </td>
      </tr>
    @endforeach
    </tbody>
  </table>
</div>
@endsection
